### PR TITLE
Support for Spark Job Server 0.9, Connection Timeouts

### PR DESCRIPTION
**Pull request by knvs97**
Support for Spark Job Server 0.9 ([SJS 0.9 Release Notes](https://github.com/spark-jobserver/spark-jobserver/releases))
     - Added support for additional key contextId in Job Response 
Support for TimeOuts while creating Connection for Requests to Spark Job Server.
    - Set Connection TImeout
    - Set Connection Request Timeout
    - Set Socket Timeout
Set Authorization Moved to Util Method.
Create Spark Job Info Moved to Util method.

### CODE REVIEW

**Comment by knvs97** [comment]
Hi @bluebreezecf,  I have made the necessary changes to support Spark Job Server 0.9 and added Support for TimeOuts HTTP Connections. Can you Review the changes and provide us with a new **RELEASE** for the Spark Job Server Client.

**Comment by knvs97** [comment]
Hi @bluebreezecf, Any update about the status of this pull request?

**Comment by knvs97** [comment]
Hi @bluebreezecf , Any update on this yet?

**Comment by bluebreezecf** [comment]
@knvs97  Thanks for you contributions  bro.

**Comment by knvs97** [comment]
Hi @bluebreezecf , When can we expect an release with the new changes?

**Pull request merged**
